<?php return array (
  'home_Name' => 'VETRONCMS',
  'admin_Name' => 'VETRONCMS',
  'home_Copyright' => 'Copyright ©2017 维畅科技',
  'home_StatisticalCode' => '345e',
  '_token' => 'BdBgV41g8qS81KBYgoQ4LQX7cnV5IlkD9Lg1yaGj',
  'home_Logo' => 'uploads/logo/20170809598aee9830108.jpg',
  'home_Icon' => 'uploads/logo/20170809598aebce17e7d.ico',
  'admin_MailDriver' => 'smtp',
  'admin_MailHost' => 'smtp.qq.com',
  'admin_MailPort' => '25',
  'admin_MailEncryption' => 'tls',
  'admin_MailSendName' => '龙锦文',
  'admin_MailSendAddress' => '396983001@qq.com',
  'admin_MailUsername' => '396983001@qq.com',
  'admin_MailUserPassword' => 'utaywaeycuopbhea',
  'home_ContactPhoneNumber' => '13512345678',
  'home_ContactEmail' => '396983001@qq.com',
  'home_ContactAddress' => '深圳市福田区上步南路1001号13C维畅科技',
  'home_ContactDescribe' => 'web,app',
  'home_SEO_Keywords' => 'SEO Keywords',
  'home_SEO_Description' => 'SEO Description',
  'testEmail' => '',
  'home_RouteModel' => '4',
);